### ISSUE TITLE
got proxy error when I don't use proxy

### ISSUE THREAD

**Issue by kjur** [mpalmer/certificate-transparency-client#1]
I didn't use any proxy and HTTP_PROXY environment variable was not defined. However I've gotten following proxy error when I run following code:

CODE:
require 'certificate-transparency-client'
ct = CT::Client.new "https://ct.googleapis.com/pilot"
p ct.get_entries(9000000)

ERROR:
/Library/Ruby/Gems/2.0.0/gems/certificate-transparency-client-0.5.1/lib/certificate-transparency/client.rb:173:in `proxy': uninitialized constant CertificateTransparency::Client::Net (NameError)
    from /Library/Ruby/Gems/2.0.0/gems/certificate-transparency-client-0.5.1/lib/certificate-transparency/client.rb:141:in`make_request'
    from /Library/Ruby/Gems/2.0.0/gems/certificate-transparency-client-0.5.1/lib/certificate-transparency/client.rb:76:in `get_sth'
    from /Library/Ruby/Gems/2.0.0/gems/certificate-transparency-client-0.5.1/lib/certificate-transparency/client.rb:98:in`get_entries'
    from t2:6:in `<main>'

Any advise?

**Comment by bortels** [comment]
certificate-transparency/client.rb has a dependency on Net::HTTP, but no require for it. 

add a " require 'net/http' " to your code as a workaround.
